package model
type health struct {
	ACTIVE_ENERGY_BURNED float32
	BASAL_ENERGY_BURNED float32
	BLOOD_GLUCOSE float32
	BLOOD_OXYGEN float32
	BLOOD_PRESSURE_DIASTOLIC float32
	BLOOD_PRESSURE_SYSTOLIC float32
	BODY_FAT_PERCENTAGE float32
	BODY_MASS_INDEX float32
	BODY_TEMPERATURE float32
	ELECTRODERMAL_ACTIVITY float32
	HEART_RATE int
	HEIGHT float32
	RESTING_HEART_RATE int
	STEPS int
	WAIST_CIRCUMFERENCE int
	WALKING_HEART_RATE int
	WEIGHT float32
	DISTANCE_WALKING_RUNNING float32
	FLIGHTS_CLIMBED int
	MOVE_MINUTES float32
	DISTANCE_DELTA float32
	MINDFULNESS float32
	SLEEP_IN_BED float32
	SLEEP_ASLEEP float32
	SLEEP_AWAKE float32
	WATER float32
	HIGH_HEART_RATE_EVENT float32
	LOW_HEART_RATE_EVENT float32
	IRREGULAR_HEART_RATE_EVENT float32
	HEART_RATE_VARIABILITY_SDNN float32

}

