development:
  dialect: postgres
  datasource: host=ec2-52-71-161-140.compute-1.amazonaws.com port=5432 user=gypzkqyxameflw password=fa0bd299af4a929d7e232ea777cde4def55217b7f0e65ec698966c5b35052c72 dbname=d5e9m1htvn9vqg sslmode=require
  dir: migrations
  table: migrations
